new blog post
rladies/blog pull request #81
Opened 2021-09-24 18:05 UTC by yabellini

Blog post about the R-Ladies metameetup for useR! 2021

2021-09-25 07:24 UTC, Athanasiamo requested changes
The Rmd's wont be knit by the current workflow. So you will need to locally knit the Rmd to md and then add the md to git. In this case, since you dont have any code chunks, I'd recommend changing the file extension from Rmd to md, and that should be all that is needed :)

2021-09-25 14:20 UTC, yabellini commented
Done! I change the file extension.  Thanks for this tip. I think we need to add these details to the contributing file.

2021-09-28 07:09 UTC, Athanasiamo approved these changes

2021-09-28 07:10 UTC, Athanasiamo commented
Let me know when you think we should merge this @ChrisZasa  :)

2021-09-29 12:00 UTC, yabellini commented on content/post/2021-09-24-r-ladies-feat-user-2021/index.en.md
> +
In this post, you will see that we have used the R-Ladies logo with the colors of the rainbow and the trans flags. We have also added a + to the R-Ladies name.
As symbols and words matter a lot, we wanted to explicitly communicate, with the use of these symbols, the importance of diversity and inclusion to our community.  We used them in this useR! to reinforce that we welcome diversity and put an effort into creating collectively a safe and friendly space.

2021-09-29 12:01 UTC, yabellini reviewed
I add the text about the logo and the plus in R-Ladies name.

2021-10-04 11:19 UTC, Athanasiamo commented
I'll merge this today, if that is ok, @yabellini  :)

2021-10-04 11:25 UTC, yabellini commented
Sure! Thanks!

2021-10-04 12:54 UTC, merged

2021-10-04 13:17 UTC, yabellini commented
Mo, the texzt about the logo is not there??